name: build-test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install project test dependencies
        run: python -m pip install -e ".[dev]"
      - name: Run tests
        run: python -m pytest
