name: Mirror to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/jv2080-group/twic-archive-manager.git
          git push gitlab --all
          git push gitlab --tags
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}